### ISSUE TITLE
Inactive Project?

### ISSUE THREAD

**Issue by Skarlett** [redcode-labs/RedNixOS#12]
The project seems to be inactive, 

is anyone out there?

**Comment by AkechiShiro** [comment]
Yes I'm still alive, and I believe the project isn't very dead yet, but I've been busy, I wanted to work on #8 and introducing CI/CD but I've been too busy with my studies, so haven't given this a try yet.

**Comment by unrooted** [comment]
Hi @Skarlett, thanks for your issue.
The project was quite inactive, I've managed to update both RedNix and RedNixOS as of today.

However, help would still be wanted, as there are still some issues with KDE (default) theming in an .iso, which I don't know the source of. This issue has been around since we've moved to flakes as of 8217c573070967cf725337b4d38eddb0751da8ea 
All I know is that the issue wasn't really there before moving to flakes, I still have a working iso with working KDE theming somewhere on my drive

Closing the issue as of right now, but feel free to raise any other issues and questions either in any of both repos or on our RCL Discord chat in [here](https://discord.gg/5jVDqcPgT7)
