### ISSUE TITLE
Feature Request: dinit

### ISSUE THREAD

**Issue by imxade** [redcode-labs/RedNixOS#4]
- add support for [dinit](https://github.com/davmac314/dinit)
- add option to configure it inside configuration.nix

(i know i'm asking for too much)

**Comment by unrooted** [comment]
Sounds cool,  I like dinit myself, however, I'm worried that we're limited by what NixOS has to offer, since RedNixOS is built on top of it. However, let's see how things will go with [this](https://github.com/NixOS/nix/pull/6558). You can also just use [RedNix](https://github.com/redcode-labs/RedNix) shells on your current OS no matter your init, as long as you have Nix installed.
